# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
